# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0005_auto_20170217_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
